
name: assignment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  shared_preferences:
  connectivity_plus:
  logger:
  audioplayers:
  audio_video_progress_bar:
  flutter_feather_icons:
  palette_generator:
  modal_bottom_sheet:
  animations:
  flutter_bounceable:
  fluttertoast :
  font_awesome_flutter:
  mockito:
  flutter_screenutil:
  device_preview:
  cupertino_icons: ^1.0.2

dependency_overrides:
  firebase_core_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
    - family: SF
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
        - asset: assets/fonts/SF-Pro-Rounded-Thin.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf